language: node_js
node_js:
  # https://github.com/nodejs/LTS
  - 'v10' # ends April 2021
  - 'v12' # ends April 2021
  - 'v13' # ends April 2021
  - 'v14' # ends April 2021

before_install:
  - npm install -g grunt-cli

install:
  - npm install

after_success:
  - grunt coveralls
